# Generated by Django 2.2.16 on 2022-01-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', '-pk'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
